project:
  type: website
  output-dir: docs

website:
  title: "Jinyang Xu - MUSA 5080 Portfolio"
  navbar:
    background: "#4b7c90"   
    foreground: "white"     
    style: "dark"
    pinned: false 
    left:
      - href: index.qmd
        text: Home
        
      - text: Weekly Notes
        menu:
        - href: weekly-notes/week-01-notes.qmd
          text: "Week 01"
        - href: weekly-notes/week-02-notes.qmd
          text: Week 02
        - href: weekly-notes/week-03-notes.qmd
          text: Week 03
        - href: weekly-notes/week-04-notes.qmd
          text: Week 04
        - href: weekly-notes/week-05-notes.qmd
          text: Week 05
        - href: weekly-notes/week-06-notes.qmd
          text: Week 06
        - href: weekly-notes/week-07-notes.qmd
          text: Week 07
        - href: weekly-notes/week-09-notes.qmd
          text: Week 09
        - href: weekly-notes/week-10-notes.qmd
          text: Week 10
        - href: weekly-notes/week-11-notes.qmd
          text: Week 11
        - href: weekly-notes/week-12-notes.qmd
          text: Week 12


      - text: Assignments
        menu:
        - href: Assignments/assignment_1/Jinyang_Xu_Assignment1.qmd
          text: "Assignment 1: Census Data Exploration"
        - href: Assignments/assignment_2/Jinyang_Xu_Assignment2.qmd
          text: "Assignment 2: Spatial Analysis and Visualization"
        - href: Assignments/assignment_4/Jinyang_Xu_Assignment4.qmd
          text: "Assignment 4: Spatial Predictive Analysis"
        - href: Assignments/assignment_5/Assignment_5_coop.qmd
          text: "Assignment 5: Space-Time Prediction of Bike Share Demand: Philadelphia Indego"
      - text: Midterm
        menu:
        - href: Assignments/midterm/slides/Jinyang_Xu_appendix1.qmd
          text: "Appendix"
        - href: Assignments/midterm/slides/Presentation_slides_final.qmd
          text: "Presentation Slides"
      - text: Final Project
        menu:
        - href: Final/Final_appendix.qmd
          text: "Appendix"
        - href: Final/Slides/Slides/Simple_context.qmd
          text: "Presentation Slides"

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    include-after-body: nav-active.html
    toc: true
    code-fold: true

    
execute:
  freeze: auto
  cache: true

  